angular.module('app')
	.controller('searchEngineController',['$scope','$state',function($scope,$state){
		$scope.home=function(){
			$state.go('footer.home');
		}
		$scope.hot=[
			{name:'休闲裤'},
			{name:'卫衣'},
			{name:'T恤'},
			{name:'毛衣'},
			{name:'牛子裤'},
			{name:'夹衣'}	
		];
		$scope.season=[
			{name:'羊毛大衣'},
			{name:'条针织衫'},
			{name:'V领织衫'},
			{name:'领棉服'},
			{name:'羽绒服'},
			{name:'羽绒夹克'}	
		];
		$scope.star=[
			{name:'运动夹克'},
			{name:'针织外套'},
			{name:'飞行夹克'},
			{name:'商务衬衫'},
			{name:'针织便西'},
			{name:'休闲棉衣'}	
		]
	}])